#pragma config(StandardModel, "RVW SQUAREBOT")
#pragma config(RenamedStdModelSensor, dgtl8, sonarCM)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//


//virtual

task main()
{
	//defining movement
	int	dist3=25; //distance in centimete
	float cir=2*PI*2.8; //circumference of wheel (cm)
	float s3= (dist3/cir)*627; //encoder counts for given distance

	//autonomous forward until obstacle
	while( SensorValue[sonarCM] > 10 || SensorValue[sonarCM] <= -1)
	{
		motor[rightMotor] = 60;
		motor[leftMotor] = 60;
	}

	//motor stops when obstacle reached
	motor[rightMotor] = 0;
	motor[leftMotor] = 0;

	//arm pulls up holding ball
	while(SensorValue[armPot] > 2000)
	{
		motor[armMotor] = -65;
	}

	//arm stops
	motor[armMotor] = 0;

	//robot backs up for 1 second
	motor[leftMotor] = -127;
	motor[rightMotor]= -127;
	wait1Msec(1000);
	motor[leftMotor] = 0;
	motor[rightMotor]=0;

	//resets motor encoders (good practice)
	nMotorEncoder[rightMotor]=0;
	nMotorEncoder[leftMotor]=0;



}
