#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, I2C_1,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_2,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Motor,  port2,           rightMotor,    tmotorVex393_MC29, PIDControl, reversed, driveRight, encoderPort, I2C_1)
#pragma config(Motor,  port3,           leftMotor,     tmotorVex393_MC29, PIDControl, driveLeft, encoderPort, I2C_2)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

void movefwrd(float value)
{
	while(nMotorEncoder[leftMotor] < value)
	{
	  motor[leftMotor] = 127;
		motor[rightMotor]= 127;
	}
	motor[leftMotor] = 0;
	motor[rightMotor]=0;
	wait1Msec(1000);

	nMotorEncoder[rightMotor]=0;
	nMotorEncoder[leftMotor]=0;
}

void reverse(float value)
{
	while(nMotorEncoder[leftMotor] > -value)
	{
	  motor[leftMotor] = -127;
		motor[rightMotor]= -127;
	}
	motor[leftMotor] = 0;
	motor[rightMotor]=0;

	nMotorEncoder[rightMotor]=0;
	nMotorEncoder[leftMotor]=0;
}


task main()
{
  float dist1 = 60.96;
  float dist2 = 121.92;
  float s1,s2;
  int count = 0;

  float cir=2*PI*2.8;


	s1= (dist1/cir)*627;
	s2= (dist2/cir)*627;


	 while(count < 3)
  	{
	movefwrd(s1);
	reverse(s1);
	movefwrd(s2);
	count++;
}

}
