#pragma config(StandardModel, "SWERVEBOT")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	SensorValue[rightEncoder] =0;
	SensorValue[leftEncoder] =0;
	//forward movement


	while( 1==1 )
	{
		motor[leftMotor] = vexRT[Ch2];
		motor[rightMotor]= vexRT[Ch3];
	}

}
