#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, I2C_1,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_2,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_3,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Motor,  port2,           rightMotor,    tmotorVex393_MC29, openLoop, reversed, driveRight, encoderPort, I2C_1)
#pragma config(Motor,  port3,           leftMotor,     tmotorVex393_MC29, openLoop, driveLeft, encoderPort, I2C_2)
#pragma config(Motor,  port6,           armmotor,      tmotorVex393_MC29, openLoop, encoderPort, I2C_3)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{

	while(vexRT[Btn7D] ==0)
	{
		//idle loop
	}
	clearTimer(T1);

	//nMotorPIDSpeedCtrl[rightMotor] = mtrSpeedReg; // PID ON
	//nMotorPIDSpeedCtrl[leftMotor] = mtrNoReg; // PID OFF

	while( time1[T1] < 3000000 )
	{
		motor[leftMotor] = vexRT[Ch3];
		motor[rightMotor]= vexRT[Ch2];

		//arm up
		if(vexRT[Btn6U] == 1)
		{
			motor[armmotor] = 30;
		}
		else
		{

			//arm down
			if(vexRT[Btn6D] == 1)
			{
				motor[armmotor] = -30;
			}
			else
			{
				motor[armmotor] = 0;
			}

		}

	}

}
