#pragma config(StandardModel, "RVW SQUAREBOT")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//


void movefwrd(float s)
{
	while(nMotorEncoder[leftMotor] < s)
	{
	  motor[leftMotor] = 63;
		motor[rightMotor]= 63;
	}
	motor[leftMotor] = 0;
	motor[rightMotor]=0;

	nMotorEncoder[rightMotor]=0;
	nMotorEncoder[leftMotor]=0;
}

void turnleft(float t)
{
	while(nMotorEncoder[rightMotor] < t)
	{
		motor[leftMotor] = 0;
		motor[rightMotor]= 63;
	}
	motor[leftMotor] = 0;
	motor[rightMotor]=0;

	nMotorEncoder[leftMotor]=0;
	nMotorEncoder[leftMotor]=0;
}

void turnright(float t)
{
	while(nMotorEncoder[leftMotor] < t)
	{
		motor[leftMotor] = 63;
		motor[rightMotor]= 0;
	}
	motor[leftMotor] = 0;
	motor[rightMotor]=0;

	nMotorEncoder[leftMotor]=0;
}


task main()
{
	float dist1,dist2,dist3,dist4;
	float cir=2*PI*2.8;
	dist1=25.5;
	dist2=30;
	dist3=4.5;
	dist4=6.5;
	float s1,s2,s3,s4;
	s1= (dist1/cir)*627;
	s2= (dist2/cir)*627;
	s3= (dist3/cir)*627;
	s4= (dist4/cir)*627;

	float arc = 0.5*2*PI*11.5;
	float turning = arc*(627/cir);

	//forward 3feet
	movefwrd(s1);

	//left-turn
	turnleft(turning);

	//forward
	movefwrd(s2);

	//right turn
	turnright(turning);

	//forward
	movefwrd(s3);

	turnright(turning);

	movefwrd(s4);
}
