#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, I2C_1,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_2,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Motor,  port2,           motorR,        tmotorVex393_MC29, PIDControl, reversed, driveRight, encoderPort, I2C_1)
#pragma config(Motor,  port3,           motorL,        tmotorVex393_MC29, PIDControl, driveLeft, encoderPort, I2C_2)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{

	motor[port2] = 127;
	motor[port3] = 127;
	wait1Msec(2500);

	motor[port2] = 127;
	motor[port3] = 0;
	wait1Msec(1250);

	motor[port2] = 127;
	motor[port3] = 127;
	wait1Msec(2100);

	motor[port2] = 0;
	motor[port3] = 127;
	wait1Msec(1200);

		motor[port2] = 127;
	motor[port3] = 127;
	wait1Msec(1100);

		motor[port2] = 0;
	motor[port3] = 127;
	wait1Msec(1300);

		motor[port2] = 127;
	motor[port3] = 127;
	wait1Msec(1050);

}
