#pragma config(StandardModel, "SWERVEBOT")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	//line tracking
	//sensor readings => 147 - 284 - 149 white in order
	//dark surface reading: 2951-2978-2962
	//threshold = (193+2964)/2 = 1578

	int threshold = 1578;

	while(true)
	{
		if(SensorValue[rightLineFollower] > threshold)
		{
			motor[leftMotor] = 63;
			motor[rightMotor] 0;
		}
		if(SensorValue[centerLineFollower] > threshold)
		{
			motor[leftMotor] = 63;
			motor[rightMotor] 63;
		}
		if(SensorValue[leftLineFollower] > threshold)
		{
			motor[leftMotor] = 0;
			motor[rightMotor] 63;
		}
	}

}
