#pragma config(StandardModel, "SQUAREBOT - IME")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

void armupdown()
{
	//arm up
	if(vexRT[Btn6U] == 1)
	{
		motor[armMotor] = 30;
	}
	else
	{

		//arm down
		if(vexRT[Btn6D] == 1)
		{
			motor[armMotor] = -30;
		}
		else
		{
			motor[armMotor] = 0;
		}

	}

}
	task main()
	{
		while(SensorValue[backTouch] == 0)
		{

		}

		while(SensorValue(frontTouch) == 0)
		{
			motor[rightMotor] = 63;
			motor[leftMotor] = 63;
		}


		while( time1[T1] < 3000000 )
		{
			motor[leftMotor] = vexRT[Ch3];
			motor[rightMotor]= vexRT[Ch2];

		}

	}
