
#pragma config(Sensor, in3,    armPot,         sensorPotentiometer)
#pragma config(Sensor, dgtl6,  frontLimit,     sensorTouch)
#pragma config(Sensor, dgtl8,  sonarCM,        sensorSONAR_cm)
#pragma config(Motor,  port2,           rightMotor,    tmotorServoContinuousRotation, openLoop, reversed)
#pragma config(Motor,  port3,           leftMotor,     tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port6,           armMotor,      tmotorServoContinuousRotation, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{


  while(vexRT[Btn7D] == 0)
  {
  }

  clearTimer(T1);
  while(time1[T1] < 90000)
  {
    motor[leftMotor] = vexRT[Ch3] / 2;
    motor[rightMotor] = vexRT[Ch2] / 2;

    if(vexRT[Btn6U] == 1 && SensorValue[armPot] <1926)
    {
      motor[armMotor] = 40;
    }
    else if(vexRT[Btn6D] == 1 && SensorValue[frontLimit]==0)
    {
      motor[armMotor] = -40;
    }
    else
    {
      motor[armMotor] = 0;
    }






  }

  motor[leftMotor] = 0;
  motor[rightMotor] = 0;

}
