#pragma config(StandardModel, "RVW SWERVEBOT")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	//turn on the robot moving forward until
	//the encoder has counted 480 degrees

	wait1Msec(2000);

	SensorValue[rightEncoder] =0;
	SensorValue[leftEncoder] =0;
	//forward movement
	while(SensorValue[rightEncoder] < 480 )
	{
		motor[leftMotor] = 60;
		motor[rightMotor] = 60;
	}

	motor[leftMotor] = 0;
	motor[rightMotor] = 0;

	SensorValue[rightEncoder] =0;
	SensorValue[leftEncoder] =0;
	//reverse movement
	while(SensorValue[rightEncoder] > -1080 )
	{
		motor[leftMotor] = -60;
		motor[rightMotor] = -60;
	}
	motor[leftMotor] = 0;
	motor[rightMotor] = 0;

}
